force-app/main/default/objects/Body_Part_Type__c/Body_Part_Type__c.object-meta.xml
<CustomObject>
    <description>An individual section of a body part set</description>
    <label>Body Part Type</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Part Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part_Type__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Body Part Types</relationshipLabel>
    <relationshipName>Body_Part_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Type__c/Body_Type__c.object-meta.xml
<CustomObject>
    <description>A template for a game of Exquisite Corpse, defining the body parts included in the game</description>
    <label>Body Type</label>
    <nameField>
        <label>Body Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/Exquisite_Corpse__c.object-meta.xml
<CustomObject>
    <description>Represents a single Exquisite Corpse drawing, with a collection of users/contributors</description>
    <label>Exquisite Corpse</label>
    <nameField>
        <label>Exquisite Corpse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exquisite Corpses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Exquisite Corpses</relationshipLabel>
    <relationshipName>Exquisite_Corpses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CorpseCreator_Test.cls
@IsTest
private class CorpseCreator_Test {
    
    @TestSetup
    static void makeData() {
        TestDataFactory.createBodyTypeWithParts();
    }

    @IsTest
    static void testGetCorpses() {
        String corpseName = 'Test Corpse';
        Body_Type__c bodyType = [SELECT Id, Name, (SELECT Id, Name FROM Body_Part_Types__r) FROM Body_Type__c LIMIT 1];

        List<Id> artistIds = new List<Id>();
        for (Body_Part_Type__c bpt : bodyType.Body_Part_Types__r) {
            artistIds.add(UserInfo.getUserId());
        }
 
        CorpseCreator.Request request = new CorpseCreator.Request();
        request.corpseName = corpseName;
        request.bodyTypeId = bodyType.Id;
        request.artistIds = artistIds;

        CorpseCreator creator = new CorpseCreator( new List<CorpseCreator.Request>{ request });

        Test.startTest();
        List<Exquisite_Corpse__c> corpses = creator.getCorpses();
        Test.stopTest();

        System.Assert.isFalse(corpses.isEmpty(), 'Should have received a corpse for the provided request');
        System.Assert.areEqual(corpseName, corpses[0].Name, 'Should have received a corpse with the provided name');
    }

    @IsTest
    static void testGetCorpsesWithInvalidUserList() {
        Body_Type__c bodyType = [SELECT Id, Name, (SELECT Id, Name FROM Body_Part_Types__r) FROM Body_Type__c LIMIT 1];

        List<Id> artistIds = new List<Id>();
        for (Body_Part_Type__c bpt : bodyType.Body_Part_Types__r) {
            artistIds.add(UserInfo.getUserId());
        }
        // Add one extra user id to create an invalid list
        artistIds.add(UserInfo.getUserId());
 
        CorpseCreator.Request request = new CorpseCreator.Request();
        request.corpseName = 'Test Corpse';
        request.bodyTypeId = bodyType.Id;
        request.artistIds = artistIds;

        CorpseCreator creator = new CorpseCreator( new List<CorpseCreator.Request>{ request });

        Test.startTest();
        try {
            creator.getCorpses();
            System.Assert.fail('Should have received an exception for the invalid user list');
        } catch (Exception e) {
            System.Assert.isTrue(e.getTypeName().contains('ExquisiteCorpseException'), 'Should have received an ExquisiteCorpseException');
            System.Assert.areEqual(CorpseCreator.INVALID_USER_LIST_MESSAGE, e.getMessage(), 'Did not receive the expected exception message');
        }
        Test.stopTest();
    }

}