force-app/main/default/objects/Body_Part__c/Body_Part__c.object-meta.xml
<CustomObject>
    <description>A section of an Exquisite Corpse drawing, assigned to an individual user</description>
    <label>Body Part</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part__c/fields/Exquisite_Corpse__c.field-meta.xml
<CustomField>
    <fullName>Exquisite_Corpse__c</fullName>
    <label>Exquisite Corpse</label>
    <referenceTo>Exquisite_Corpse__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Body_Type__c/Body_Type__c.object-meta.xml
<CustomObject>
    <description>A template for a game of Exquisite Corpse, defining the body parts included in the game</description>
    <label>Body Type</label>
    <nameField>
        <label>Body Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/Exquisite_Corpse__c.object-meta.xml
<CustomObject>
    <description>Represents a single Exquisite Corpse drawing, with a collection of users/contributors</description>
    <label>Exquisite Corpse</label>
    <nameField>
        <label>Exquisite Corpse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exquisite Corpses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Exquisite Corpses</relationshipLabel>
    <relationshipName>Exquisite_Corpses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExquisiteCorpseService_Test.cls
@IsTest
private class ExquisiteCorpseService_Test {

    @TestSetup
    static void makeData() {
        Body_Type__c bodyType = TestDataFactory.createBodyTypeWithParts();
        TestDataFactory.createCorpse(bodyType);
    }

    @IsTest
    static void testHandleCompletedCorpses() {
        Exquisite_Corpse__c corpse = [SELECT Id, Status__c, Completed_Date_Time__c FROM Exquisite_Corpse__c LIMIT 1];
        corpse.Status__c = 'Complete';

        Test.startTest();
        update corpse;
        Test.stopTest();

        Exquisite_Corpse__c refreshedCorpse = [SELECT Id, Status__c, Completed_Date_Time__c FROM Exquisite_Corpse__c WHERE Id = :corpse.Id LIMIT 1];
        System.Assert.isNotNull(refreshedCorpse.Completed_Date_Time__c, 'Should have received a completed date/time');
    }

    @IsTest
    static void testRenameBodyParts() {
        Exquisite_Corpse__c corpse = [SELECT Id, Name FROM Exquisite_Corpse__c LIMIT 1];
        corpse.Name = 'A very new name';

        Test.startTest();
        update corpse;
        Test.stopTest();

        List<Body_Part__c> bodyParts = [SELECT Name FROM Body_Part__c WHERE Exquisite_Corpse__c = :corpse.Id];
        for (Body_Part__c bodyPart : bodyParts) {
            System.Assert.isTrue(bodyPart.Name.contains(corpse.Name), 'Body part name should contain the new corpse name');
        }
    }
    
}