force-app/main/default/objects/Body_Part__c/Body_Part__c.object-meta.xml
<CustomObject>
    <description>A section of an Exquisite Corpse drawing, assigned to an individual user</description>
    <label>Body Part</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part__c/fields/Body_Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Part_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Part Type</label>
    <referenceTo>Body_Part_Type__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Exquisite_Corpse__c.field-meta.xml
<CustomField>
    <fullName>Exquisite_Corpse__c</fullName>
    <label>Exquisite Corpse</label>
    <referenceTo>Exquisite_Corpse__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <formula>Body_Part_Type__r.Sort_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Body_Part_Type__c/Body_Part_Type__c.object-meta.xml
<CustomObject>
    <description>An individual section of a body part set</description>
    <label>Body Part Type</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Part Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part_Type__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Body Part Types</relationshipLabel>
    <relationshipName>Body_Part_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part_Type__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which body parts of this type should appear within the set, from top to bottom of the drawing</description>
    <inlineHelpText>The order in which body parts of this type should appear within the set, from top to bottom of the drawing</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Body_Type__c/Body_Type__c.object-meta.xml
<CustomObject>
    <description>A template for a game of Exquisite Corpse, defining the body parts included in the game</description>
    <label>Body Type</label>
    <nameField>
        <label>Body Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/Exquisite_Corpse__c.object-meta.xml
<CustomObject>
    <description>Represents a single Exquisite Corpse drawing, with a collection of users/contributors</description>
    <label>Exquisite Corpse</label>
    <nameField>
        <label>Exquisite Corpse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exquisite Corpses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Exquisite Corpses</relationshipLabel>
    <relationshipName>Exquisite_Corpses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CorpseCreator.cls
public with sharing class CorpseCreator {

    /*
    private List<Exquisite_Corpse__c> corpses;
    private Map<Id, Body_Type__c> bodyTypesWithParts;

    public CorpseCreator(List<Exquisite_Corpse__c> corpses) {
        this.corpses = corpses;
        this.bodyTypesWithParts = loadBodyTypeMap();
    }

    public static List<Body_Part__c> createBodyParts() {
        List<Body_Part__c> bodyParts = new List<Body_Part__c>();
        for (Exquisite_Corpse__c corpse : corpses) {
            Body_Type__c bodyType = bodyTypesWithParts.get(corpse.Body_Type__c);
            for (Body_Part_Type__c bpt : bodyType.Body_Part_Types__r) {
                bodyParts.add(
                    new Body_Part__c(
                        Exquisite_Corpse__c = corpse.Id,
                        Body_Part_Type__c = bpt.Id
                    )
                );
            }
        }
        insert bodyParts;
        return bodyParts;
    }

    private static Map<Id, Body_Type__c> loadBodyTypeMap() {
        Set<Id> bodyTypeIds = new Set<Id>();
        for (Exquisite_Corpse__c corpse : corpses) {
            bodyTypeIds.add(corpse.Body_Type__c);
        }

        return new Map<Id, Body_Part__c>([
            SELECT Id, Name,
                   (SELECT Id, Name, Sort_Order__c FROM Body_Part_Types__r)
              FROM Body_Type__c
             WHERE Id IN :bodyTypeIds
        ]);
    }
        */
}