force-app/main/default/objects/Body_Part__c/Body_Part__c.object-meta.xml
<CustomObject>
    <description>A section of an Exquisite Corpse drawing, assigned to an individual user</description>
    <label>Body Part</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part__c/fields/Exquisite_Corpse__c.field-meta.xml
<CustomField>
    <fullName>Exquisite_Corpse__c</fullName>
    <label>Exquisite Corpse</label>
    <referenceTo>Exquisite_Corpse__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <formula>Body_Part_Type__r.Sort_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exquisite_Corpse__c/Exquisite_Corpse__c.object-meta.xml
<CustomObject>
    <description>Represents a single Exquisite Corpse drawing, with a collection of users/contributors</description>
    <label>Exquisite Corpse</label>
    <nameField>
        <label>Exquisite Corpse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exquisite Corpses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BodyPartCompletionHandler.cls
/******************************************************************
 * @description When a body part record is completed, handle related actions
 *   - If additional body parts are waiting, update the next record's status to In Progress
 *   - If no additional body parts are waiting, update the corpse status to Complete
 * 
 * @author SerkinSolutions
 * @date 2025
 ******************************************************************/
public without sharing class BodyPartCompletionHandler {
    
    private static final String STATUS_COMPLETE = 'Complete';
    private static final String STATUS_IN_PROGRESS = 'In Progress';
    private static final String STATUS_WAITING = 'Waiting';

    private List<Body_Part__c> completedBodyParts;
    private List<Body_Part__c> bodyPartsToUpdate;
    private List<Exquisite_Corpse__c> completedCorpses;
    
    public BodyPartCompletionHandler(List<Body_Part__c> completedBodyParts) {
        this.completedBodyParts = completedBodyParts;
        this.bodyPartsToUpdate = new List<Body_Part__c>();
        this.completedCorpses = new List<Exquisite_Corpse__c>();
    }

    public void run() {
        List<Exquisite_Corpse__c> corpsesWithNextPart = getCorpsesWithNextBodyPart();
        for (Exquisite_Corpse__c corpse : getCorpsesWithNextBodyPart()) {
            if (!corpse.Body_Parts__r.isEmpty()) {
                Body_Part__c nextPart = corpse.Body_Parts__r[0];
                nextPart.Status__c = STATUS_IN_PROGRESS;
                bodyPartsToUpdate.add(nextPart);
            } else {
                corpse.Status__c = STATUS_COMPLETE;
                completedCorpses.add(corpse);
            }
        }
        commitChanges();
    }

    private List<Exquisite_Corpse__c> getCorpsesWithNextBodyPart() {
        Set<Id> corpseIds = getCorpseIds();
        return [
            SELECT Id, Status__c, 
                   (SELECT Id, Status__c 
                      FROM Body_Parts__r 
                     WHERE Status__c = :STATUS_WAITING 
                     ORDER BY Sort_Order__c ASC 
                     LIMIT 1)
              FROM Exquisite_Corpse__c
             WHERE Id IN :corpseIds
              WITH SYSTEM_MODE
        ];
    }

    private Set<Id> getCorpseIds() {
        Set<Id> corpseIds = new Set<Id>();
        for (Body_Part__c bp : completedBodyParts) {
            corpseIds.add(bp.Exquisite_Corpse__c);
        }
        return corpseIds;
    }

    private void commitChanges() {
        List<SObject> sobjectsToUpdate = new List<SObject>();
        sobjectsToUpdate.addAll(bodyPartsToUpdate);
        sobjectsToUpdate.addAll(completedCorpses);
        Database.update(sobjectsToUpdate, AccessLevel.SYSTEM_MODE);
    }

}