force-app/main/default/objects/Body_Part__c/Body_Part__c.object-meta.xml
<CustomObject>
    <description>A section of an Exquisite Corpse drawing, assigned to an individual user</description>
    <label>Body Part</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part__c/fields/Exquisite_Corpse__c.field-meta.xml
<CustomField>
    <fullName>Exquisite_Corpse__c</fullName>
    <label>Exquisite Corpse</label>
    <referenceTo>Exquisite_Corpse__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <formula>Body_Part_Type__r.Sort_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Body_Type__c/Body_Type__c.object-meta.xml
<CustomObject>
    <description>A template for a game of Exquisite Corpse, defining the body parts included in the game</description>
    <label>Body Type</label>
    <nameField>
        <label>Body Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/Exquisite_Corpse__c.object-meta.xml
<CustomObject>
    <description>Represents a single Exquisite Corpse drawing, with a collection of users/contributors</description>
    <label>Exquisite Corpse</label>
    <nameField>
        <label>Exquisite Corpse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exquisite Corpses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Exquisite Corpses</relationshipLabel>
    <relationshipName>Exquisite_Corpses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BodyPartCompletionHandler_Test.cls
@IsTest
private class BodyPartCompletionHandler_Test {
    
    @TestSetup
    static void makeData() {
        Body_Type__c bodyType = TestDataFactory.createBodyTypeWithParts();
        TestDataFactory.createCorpse(bodyType);
    }

    @IsTest
    static void testCompletedRecord() {
        Body_Part__c bodyPart = [SELECT Id, Exquisite_Corpse__c, Sort_Order__c, Status__c FROM Body_Part__c WHERE Status__c = 'In Progress' LIMIT 1];
        bodyPart.Status__c = 'Complete';

        Test.startTest();
        update bodyPart;
        Test.stopTest();

        Exquisite_Corpse__c corpse = [
            SELECT Id, (SELECT Id, Sort_Order__c FROM Body_Parts__r WHERE Status__c = 'In Progress' ORDER BY Sort_Order__c ASC) 
              FROM Exquisite_Corpse__c
             WHERE Id = :bodyPart.Exquisite_Corpse__c
             LIMIT 1
        ];

        System.Assert.isFalse(corpse.Body_Parts__r.isEmpty(), 'Should have received the next in progress body part');
        System.Assert.areNotEqual(bodyPart.Id, corpse.Body_Parts__r[0].Id, 'Should not have received the original body part record');
        System.Assert.isTrue(corpse.Body_Parts__r[0].Sort_Order__c > bodyPart.Sort_Order__c, 'The new record\'s sort order should be greater than the original record\'s');
    }

}