force-app/main/default/objects/Body_Part__c/Body_Part__c.object-meta.xml
<CustomObject>
    <description>A section of an Exquisite Corpse drawing, assigned to an individual user</description>
    <label>Body Part</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Artist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Body_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Body_Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Part_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Part Type</label>
    <referenceTo>Body_Part_Type__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Exquisite_Corpse__c.field-meta.xml
<CustomField>
    <fullName>Exquisite_Corpse__c</fullName>
    <label>Exquisite Corpse</label>
    <referenceTo>Exquisite_Corpse__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Body_Part_Type__c/Body_Part_Type__c.object-meta.xml
<CustomObject>
    <description>An individual section of a body part set</description>
    <label>Body Part Type</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Part Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part_Type__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Body Part Types</relationshipLabel>
    <relationshipName>Body_Part_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Type__c/Body_Type__c.object-meta.xml
<CustomObject>
    <description>A template for a game of Exquisite Corpse, defining the body parts included in the game</description>
    <label>Body Type</label>
    <nameField>
        <label>Body Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/Exquisite_Corpse__c.object-meta.xml
<CustomObject>
    <description>Represents a single Exquisite Corpse drawing, with a collection of users/contributors</description>
    <label>Exquisite Corpse</label>
    <nameField>
        <label>Exquisite Corpse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exquisite Corpses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Exquisite Corpses</relationshipLabel>
    <relationshipName>Exquisite_Corpses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BodyPartNamer_Test.cls
@IsTest
private class BodyPartNamer_Test {
    
    @TestSetup
    static void makeData() {
        TestDataFactory.createBodyTypeWithParts();
    }

    @IsTest
    static void testAutoName() {
        Body_Type__c bodyType = [SELECT Id, Name, (SELECT Id, Name FROM Body_Part_Types__r LIMIT 1) FROM Body_Type__c LIMIT 1];
        Body_Part_Type__c partType = bodyType.Body_Part_Types__r[0];
        Exquisite_Corpse__c corpse = new Exquisite_Corpse__c(Name = 'TestCorpse', Body_Type__c = bodyType.Id, Status__c = 'In Progress');
        insert corpse;

        Body_Part__c bodyPart = new Body_Part__c(
            Exquisite_Corpse__c = corpse.Id, 
            Body_Part_Type__c = partType.Id,
            Artist__c = UserInfo.getUserId(),
            Status__c = 'In Progress'
        );
        Test.startTest();
        new BodyPartNamer( new List<Body_Part__c>{ bodyPart } ).autoName();
        Test.stopTest();

        System.Assert.isNotNull(bodyPart.Name, 'The body part should have received a name');
        System.Assert.isTrue(bodyPart.Name.contains(corpse.Name), 'The auto name should include the corpse name');
        System.Assert.isTrue(bodyPart.Name.contains(partType.Name), 'The auto name should include the body part type name');
        System.Assert.isTrue(bodyPart.Name.contains(UserInfo.getFirstName()), 'The auto name should include the artist\'s first name');
    }

    @IsTest
    static void testAutoNameWithoutArtist() {
        Body_Type__c bodyType = [SELECT Id, Name, (SELECT Id, Name FROM Body_Part_Types__r LIMIT 1) FROM Body_Type__c LIMIT 1];
        Body_Part_Type__c partType = bodyType.Body_Part_Types__r[0];
        Exquisite_Corpse__c corpse = new Exquisite_Corpse__c(Name = 'TestCorpse', Body_Type__c = bodyType.Id, Status__c = 'In Progress');
        insert corpse;

        // Create body part without an artist defined
        Body_Part__c bodyPart = new Body_Part__c(
            Exquisite_Corpse__c = corpse.Id, 
            Body_Part_Type__c = partType.Id,
            Status__c = 'In Progress'
        );

        Test.startTest();
        new BodyPartNamer( new List<Body_Part__c>{ bodyPart } ).autoName();
        Test.stopTest();

        System.Assert.isNotNull(bodyPart.Name, 'The body part should have received a name');
        System.Assert.isTrue(bodyPart.Name.contains(corpse.Name), 'The auto name should include the corpse name');
        System.Assert.isTrue(bodyPart.Name.contains(partType.Name), 'The auto name should include the body part type name');
    }

}