force-app/main/default/objects/Body_Part__c/Body_Part__c.object-meta.xml
<CustomObject>
    <description>A section of an Exquisite Corpse drawing, assigned to an individual user</description>
    <label>Body Part</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Artist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Body_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Body_Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Part_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Part Type</label>
    <referenceTo>Body_Part_Type__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Exquisite_Corpse__c.field-meta.xml
<CustomField>
    <fullName>Exquisite_Corpse__c</fullName>
    <label>Exquisite Corpse</label>
    <referenceTo>Exquisite_Corpse__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <formula>Body_Part_Type__r.Sort_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Body_Part_Type__c/Body_Part_Type__c.object-meta.xml
<CustomObject>
    <description>An individual section of a body part set</description>
    <label>Body Part Type</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Part Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part_Type__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Body Part Types</relationshipLabel>
    <relationshipName>Body_Part_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part_Type__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which body parts of this type should appear within the set, from top to bottom of the drawing</description>
    <inlineHelpText>The order in which body parts of this type should appear within the set, from top to bottom of the drawing</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Body_Type__c/Body_Type__c.object-meta.xml
<CustomObject>
    <description>A template for a game of Exquisite Corpse, defining the body parts included in the game</description>
    <label>Body Type</label>
    <nameField>
        <label>Body Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/Exquisite_Corpse__c.object-meta.xml
<CustomObject>
    <description>Represents a single Exquisite Corpse drawing, with a collection of users/contributors</description>
    <label>Exquisite Corpse</label>
    <nameField>
        <label>Exquisite Corpse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exquisite Corpses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Type</label>
    <referenceTo>Body_Type__c</referenceTo>
    <relationshipLabel>Exquisite Corpses</relationshipLabel>
    <relationshipName>Exquisite_Corpses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BodyPartNamer.cls
/******************************************************************
 * @description Handle naming of new body part records
 * 
 * @author SerkinSolutions
 * @date 2025
 ******************************************************************/
public with sharing class BodyPartNamer {

    public static void autoName(List<Body_Part__c> bodyParts) {
        Map<Id, Body_Part_Type__c> bodyPartTypeMap = getBodyPartTypeMap(bodyParts);
        Map<Id, Exquisite_Corpse__c> corpseMap = getCorpseMap(bodyParts);
        Map<Id, User> userMap = getUserMap(bodyParts);
        for (Body_Part__c bp : bodyParts) {
            Body_Part_Type__c partType = bodyPartTypeMap.get(bp.Body_Part_Type__c);
            Exquisite_Corpse__c corpse = corpseMap.get(bp.Exquisite_Corpse__c);
            String newName = corpse.Name + ' ' + partType.Name;
            if (bp.Artist__c != null && userMap.containsKey(bp.Artist__c)) {
                newName += ' - ' + userMap.get(bp.Artist__c).FirstName;
            }
            bp.Name = newName.left(80);
        }
    }

    private static Map<Id, Exquisite_Corpse__c> getCorpseMap(List<Body_Part__c> bodyParts) {
        Set<Id> corpseIds = new Set<Id>();
        for (Body_Part__c bp : bodyParts) {
            corpseIds.add(bp.Exquisite_Corpse__c);
        }

        return new Map<Id, Exquisite_Corpse__c>([
            SELECT Id, Name
              FROM Exquisite_Corpse__c
             WHERE Id IN :corpseIds
        ]);
    }

    private static Map<Id, Body_Part_Type__c> getBodyPartTypeMap(List<Body_Part__c> bodyParts) {
        Set<Id> bptIds = new Set<Id>();
        for (Body_Part__c bp : bodyParts) {
            bptIds.add(bp.Body_Part_Type__c);
        }

        return new Map<Id, Body_Part_Type__c>([
            SELECT Id, Name, Body_Type__r.Name
              FROM Body_Part_Type__c
             WHERE Id IN :bptIds
             ORDER BY Sort_Order__c ASC
        ]);
    }

    private static Map<Id, User> getUserMap(List<Body_Part__c> bodyParts) {
        Set<Id> userIds = new Set<Id>();
        for (Body_Part__c bp : bodyParts) {
            if (bp.Artist__c != null) {
                userIds.add(bp.Artist__c);
            }
        }

        return new Map<Id, User>([
            SELECT Id, FirstName, LastName, Email
              FROM User
             WHERE Id IN :userIds
        ]);
    }

}