force-app/main/default/objects/Body_Part__c/Body_Part__c.object-meta.xml
<CustomObject>
    <description>A section of an Exquisite Corpse drawing, assigned to an individual user</description>
    <label>Body Part</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Artist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Body_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Body_Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Part_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Part Type</label>
    <referenceTo>Body_Part_Type__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Exquisite_Corpse__c.field-meta.xml
<CustomField>
    <fullName>Exquisite_Corpse__c</fullName>
    <label>Exquisite Corpse</label>
    <referenceTo>Exquisite_Corpse__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <formula>Body_Part_Type__r.Sort_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Body_Part_Type__c/Body_Part_Type__c.object-meta.xml
<CustomObject>
    <description>An individual section of a body part set</description>
    <label>Body Part Type</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Part Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part_Type__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which body parts of this type should appear within the set, from top to bottom of the drawing</description>
    <inlineHelpText>The order in which body parts of this type should appear within the set, from top to bottom of the drawing</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exquisite_Corpse__c/Exquisite_Corpse__c.object-meta.xml
<CustomObject>
    <description>Represents a single Exquisite Corpse drawing, with a collection of users/contributors</description>
    <label>Exquisite Corpse</label>
    <nameField>
        <label>Exquisite Corpse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exquisite Corpses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BodyPart.cls
public class BodyPart {

    /**
     * Body Part Information
     */
    @AuraEnabled
    public Id id;

    @AuraEnabled
    public String name;

    @AuraEnabled
    public Decimal sortOrder;

    @AuraEnabled
    public String status;

    /**
     * Body Part Type Information
     */
    @AuraEnabled
    public String bodyPartType;

    /**
     * Exquisite Corpse Information
     */
    @AuraEnabled
    public String corpseName;

    @AuraEnabled
    public String corpseStatus;

    /**
     * Assigned User Information
     */
    @AuraEnabled
    public Id artistId;

    @AuraEnabled
    public String artistFirstName;

    @AuraEnabled
    public String artistLastName;

    @AuraEnabled
    public String artistEmail;

    /**
     * Create a body part from a Body_Part__c sobject
     * Must include all data from parent objects
     */
    public BodyPart(Body_Part__c sobj) {
        this.id = sobj.Id;
        this.name = sobj.Name;
        this.sortOrder = sobj.Sort_Order__c;
        this.status = sobj.Status__c;
        this.corpseName = sobj.Exquisite_Corpse__r.Name;
        this.corpseStatus = sobj.Exquisite_Corpse__r.Status__c;
        this.bodyPartType = sobj.Body_Part_Type__r.Name;
        this.artistId = sobj.Artist__c;
        this.artistFirstName = sobj.Artist__r.FirstName;
        this.artistLastName = sobj.Artist__r.LastName;
        this.artistEmail = sobj.Artist__r.Email;
    }

}