force-app/main/default/objects/Body_Part__c/Body_Part__c.object-meta.xml
<CustomObject>
    <description>A section of an Exquisite Corpse drawing, assigned to an individual user</description>
    <label>Body Part</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Body_Part__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Artist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Body_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Body_Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Part_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Body Part Type</label>
    <referenceTo>Body_Part_Type__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Exquisite_Corpse__c.field-meta.xml
<CustomField>
    <fullName>Exquisite_Corpse__c</fullName>
    <label>Exquisite Corpse</label>
    <referenceTo>Exquisite_Corpse__c</referenceTo>
    <relationshipLabel>Body Parts</relationshipLabel>
    <relationshipName>Body_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Body_Part__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting</fullName>
                <default>true</default>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Body_Part_Type__c/Body_Part_Type__c.object-meta.xml
<CustomObject>
    <description>An individual section of a body part set</description>
    <label>Body Part Type</label>
    <nameField>
        <label>Body Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Body Part Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/Exquisite_Corpse__c.object-meta.xml
<CustomObject>
    <description>Represents a single Exquisite Corpse drawing, with a collection of users/contributors</description>
    <label>Exquisite Corpse</label>
    <nameField>
        <label>Exquisite Corpse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exquisite Corpses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exquisite_Corpse__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExquisiteCorpseService.cls
/******************************************************************
 * @description Exquisite Corpse Service
 * 
 * @author SerkinSolutions
 * @date 2025
 ******************************************************************/
public with sharing class ExquisiteCorpseService {

    private static final String STATUS_COMPLETE = 'Complete';

    private List<Exquisite_Corpse__c> newList;
    private Map<Id, Exquisite_Corpse__c> oldMap;

    public ExquisiteCorpseService(List<Exquisite_Corpse__c> newList, Map<Id, Exquisite_Corpse__c> oldMap) {
        this.newList = newList;
        this.oldMap = oldMap;
    }
    
    /**
     * Stamp the completed date/time for newly completed corpses
     */
    public void handleCompletedCorpses() {
        for (Exquisite_Corpse__c corpse : newList) {
            if (corpse.Status__c == STATUS_COMPLETE && oldMap.get(corpse.Id).Status__c != STATUS_COMPLETE) {
                corpse.Completed_Date_Time__c = Datetime.now();
            }
        }
    }

    /**
     * Re-name all child body parts
     */
    public void renameBodyParts() {
        List<Exquisite_Corpse__c> corpsesWithNameChanges = filterToCorpsesWithNameChanges();
        if (!corpsesWithNameChanges.isEmpty()) {
            List<Body_Part__c> bodyPartsToRename = getBodyPartsForCorpses(corpsesWithNameChanges);
            bodyPartsToRename = new BodyPartNamer(bodyPartsToRename).autoName();
            Database.update(bodyPartsToRename, AccessLevel.SYSTEM_MODE);
        }
    }

    /**
     * Filter records in trigger to corpses with name changes
     */
    private List<Exquisite_Corpse__c> filterToCorpsesWithNameChanges() {
        List<Exquisite_Corpse__c> filteredCorpses = new List<Exquisite_Corpse__c>();
        for (Exquisite_Corpse__c corpse : newList) {
            if (corpse.Name != oldMap.get(corpse.Id).Name) {
                filteredCorpses.add(corpse);
            }
        }
        return filteredCorpses;
    }

    private static List<Body_Part__c> getBodyPartsForCorpses(List<Exquisite_Corpse__c> corpses) {
        return [
            SELECT Id, Body_Part_Type__c, Artist__c, Exquisite_Corpse__c
              FROM Body_Part__c
             WHERE Exquisite_Corpse__c IN :corpses
              WITH SYSTEM_MODE
        ];
    }

}